config/routes.rb
Rails.application.routes.draw do

  resources :events, :pages, :users

  get '/' => 'pages#index', :as => :root

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/team' => 'pages#team'

  #/session/new - login form
  get '/login' => 'session#new'

  #/session - after submit form for login
    post '/login' => 'session#create'

  #/session - logout
    delete '/logout' => 'session#destroy'

  # add a logged in user to an event
  	post 'events/:id/join' => 'users#join_event'

  # namespaces the admin to /admin/* paths
  namespace :admins do
    resources :events, :users
    resources :attendees #, :except => [:edit]
    # resources :pages, :only => [:show]
    get '/' => 'pages#show'        # this is not root. This is /admins
  end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :attendees
	has_many :events, through: :attendees
	validates :email, uniqueness: true
	validates :name, :email, presence: true
  
  validates :password, presence: true, :on => :create
  mount_uploader :photo, PhotoUploader
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < AdminsController
  before_action :check_if_admin

  def create
    @user = User.new(user_params)
  end

  def new
    @user = User.new
  end

  def index
    @users = User.order('name')
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to '/admins/users'
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to '/admins/users'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :bio, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def show
		@events = current_user.events.order('date_time')
	end

	def create
		@event = Event.find(params[:user][:event_id])

		# create a new user
		@user = User.new(
			name: params[:user][:name],
			email: params[:user][:email],
			password: params[:user][:password],
			admin: false)

		if @user.save
			# Log the user in
			session[:user_id] = @user.id

			# Assign this user to the talk they wanted
			new_attendee = Attendee.new(user_id: @user.id, event_id: @event.id, user_role: 'user')
			if new_attendee.save
      	redirect_to user_path(@user.id), notice: "Woohoo! Your ticket has been booked!"
    	else
    		redirect_to :back, notice: "Something went wrong! Please try again."
    	end
    else
      redirect_to root_path, notice: "Your ticket could not be confirmed. Please try again."
    end
	end

	# joins a logged in user to an event without asking for their details again
	def join_event
		event = Event.find(params[:id])

		# don't add them if they are already attending this event
		unless event.attendees.find_by(user_id: current_user.id)
			new_attendee = Attendee.new(user_id: current_user.id, event_id: params[:id], user_role: 'user')

			# couldn't save the user to this event for some reason
			unless new_attendee.save
	  		render "events/show", notice: "Something went wrong! Please try again."
	  	end
	  end
	  redirect_to user_path(current_user.id), notice: "Woohoo! Your ticket has been booked!"
	end

end

app/views/admins/users/_form.html.erb
 <%= form_for [:admins, @user] do |f| %> <!--need :admins since namespaced-->
     <div class="admin">
        <fieldset>
            <legend>User</legend>
            <p><%= f.label :name, :class =>'field' %></p>
            <p><%= f.text_field :name, :class =>'textbox-300' %></p>

            <p><%= f.label :email, :class =>'field' %></p>
            <p><%= f.text_field :email, :class =>'textbox-300'  %></p>

<!--         commented out because user_role was moved to attendees table and don't know how to fix it. JLW.
             <p><%#= f.label :user_role, :class =>'field' %></p>
             <p><#%= f.text_field :role, :class =>'textbox-300'  %></p>
-->
             <p><%= f.label :bio, :class =>'field' %></p>
             <p><%= f.text_field :bio, :class =>'textbox-300'  %></p>
             
             <%= image_tag(@user.photo_url) if @user.photo? %>
             <p> 
                <label for="">Upload File</label>
                <%= f.file_field :photo %>
             </p> 

             <p><%= f.submit :class =>'admin-btn'%></p>
         </fieldset>
     </div>
 <% end %>

app/views/admins/users/index.html.erb
<div class="admin-pages">
    <h2>Users</h2>
    <table class="admin" border="1">
      <tr>
        <th>Name</th>
            <th></th>
            <th></th>
        </tr>
        <% @users.each do |user| %>
            <tr>
                <td class="admin-left"><%= link_to user.name, admins_user_path(user) %></td>
                <td><%= link_to 'Edit', edit_admins_user_path(user) %></td>

                <td><%= link_to 'Delete', admins_user_path(user), method: :delete %></td>
            </tr>
        <% end %>
    </table>

    <%= render :partial => 'admins/pages/admin' %>
</div>

app/views/admins/users/new.html.erb
<h2>new user</h2>

<%= form_for [:admins, @user] do |f| %>

    <%= render 'form' %>

<% end %>

<%= render :partial => 'admins/pages/admin' %>

app/views/admins/users/show.html.erb
<h1><%= @user.name %></h1>
<h3><%= @user.email %></h3>
<h3><%= @user.bio %></h3>

<%= render :partial => 'admins/pages/admin' %>