config/routes.rb
Rails.application.routes.draw do

  resources :events, :pages, :users

  get '/' => 'pages#index', :as => :root

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/team' => 'pages#team'

  #/session/new - login form
  get '/login' => 'session#new'

  #/session - after submit form for login
    post '/login' => 'session#create'

  #/session - logout
    delete '/logout' => 'session#destroy'

  # add a logged in user to an event
  	post 'events/:id/join' => 'users#join_event'

  # namespaces the admin to /admin/* paths
  namespace :admins do
    resources :events, :users
    resources :attendees #, :except => [:edit]
    # resources :pages, :only => [:show]
    get '/' => 'pages#show'        # this is not root. This is /admins
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :attendees
	has_many :users, through: :attendees
	validates :title, :description, :date_time, :max_tix ,presence: true


	def speaker
		User.find(self.attendees.find_by(user_role: 'speaker').user_id)
	end

	def tickets_sold
		self.attendees.where(user_role: 'user').count
	end

	def tickets_available
		max_tix = self.max_tix
		tix_sold = self.tickets_sold
		max_tix - tix_sold
	end

	def new_speaker_id
		self.attendees.find_by(user_role: 'speaker').user_id
	end
end

app/controllers/admins/events_controller.rb
class Admins::EventsController < AdminsController
  before_action :check_if_admin

  def create
    @event = Event.new(event_params)
  end

  def new
    @event = Event.new
  end

  def index
    @events = Event.order('date_time')
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    # set current speaker's role to 'user'
    current_speaker = @event.attendees.find_by(user_role: 'speaker')
    current_speaker.user_role = 'user'
    current_speaker.save

    # assign the role of 'speaker' to the selected attendee
    new_speaker = @event.attendees.find_by(user_id: params[:event][:new_speaker_id])
    new_speaker.user_role = 'speaker'
    new_speaker.save

    if @event.update(event_params.slice!(:new_speaker_id))
    # must remove new_speaker_id from the returned hash as it's not part of event
      redirect_to '/admins/events'
    else
      render :edit
    end
  end

  def edit
    @event = Event.find(params[:id])
    @user_list = @event.users.order('user_id')
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to '/admins/events'
  end

  private

    def event_params
      params.require(:event).permit(:title, :description, :date_time, :max_tix, :new_speaker_id)
      # must include new_speaker_id here so it's returned by the form
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def show
		@user = User.new
		@event = Event.find(params[:id])
		@users = @event.users
	end

end

app/views/admins/events/_form.html.erb
 <%= form_for [:admins, @event] do |f| %>  <!--need :admins since namespaced-->
     <div class="admin">
        <fieldset>
            <legend>event</legend>
            <p><%= f.label :title, :class =>'admin-field' %></p>
            <p><%= f.text_field :title, :class =>'textbox-300' %></p>

            <p><%= f.label :description, :class =>'admin-field' %></p>
            <p><%= f.text_field :description, :class =>'textbox-300' %></p>

            <p><%= f.label :date_time, :class =>'admin-field' %></p>
            <p><%= f.datetime_local_field :date_time, :class =>'textbox-300' %></p>     <!--can't call this datetime_field because it is a helper??-->

            <p><%= f.label :max_tix, :class =>'admin-field' %></p>
            <p><%= f.text_field :max_tix, :class =>'textbox-300' %></p>

            <p><%= f.label "Speaker", :class =>'admin-field' %></p>
            <p><%= f.collection_select(:new_speaker_id,@user_list,:id,:name) %></p>

            <p><%= f.submit :class =>'admin-btn' %></p>
         </fieldset>
     </div>
 <% end %>

 <!--http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html-->

app/views/admins/events/edit.html.erb
<%= render 'form' %>

<%= render :partial => 'admins/pages/admin' %>

app/views/admins/events/index.html.erb
<div class="admin-pages">
    <h2>Events</h2>

    <table class="admin" border="1">
      <tr><th>Title</th><th>Time</th><th>Tickets Sold</th><th>Maximum Tickets</th><th></th><th></th></tr>
    <% @events.each do |event| %>
        <tr>
            <!-- <td class="admin-left"><%#= link_to event.title, admins_event_path(event) %></td> -->
            <td class="admin-left"><%= event.title %></td>
            <td><%= event.date_time.to_s[11,5] %></td>
            <td><%= event.tickets_sold %></td>
            <td><%= event.max_tix %></td>
            <td><%= link_to 'Edit', edit_admins_event_path(event) %></td>

            <td><%= link_to 'Delete', admins_event_path(event), method: :delete %></td>
        </tr>
    <% end %>
    </table>

    <%= render :partial => 'admins/pages/admin' %>
</div>

app/views/admins/events/show.html.erb
<h1><%= @event.title %></h1>
<h2><%= @event.description %></h2>
<h2><%= @event.date_time %></h2>
<h2><%= @event.max_tix %></h2>

<%= render :partial => 'admins/pages/admin' %>