config/routes.rb
Rails.application.routes.draw do

  resources :events, :pages, :users

  get '/' => 'pages#index', :as => :root

  get '/about' => 'pages#about'

  get '/contact' => 'pages#contact'

  get '/team' => 'pages#team'

  #/session/new - login form
  get '/login' => 'session#new'

  #/session - after submit form for login
    post '/login' => 'session#create'

  #/session - logout
    delete '/logout' => 'session#destroy'

  # add a logged in user to an event
  	post 'events/:id/join' => 'users#join_event'

  # namespaces the admin to /admin/* paths
  namespace :admins do
    resources :events, :users
    resources :attendees #, :except => [:edit]
    # resources :pages, :only => [:show]
    get '/' => 'pages#show'        # this is not root. This is /admins
  end

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :event
	belongs_to :user

  def number_attendees
    self.attendees.where(user_role: 'user').count
  end

  def tickets_available
    max_tix = self.max_tix
    tix_sold = number_attendees
    max_tix - tix_sold
  end

  def attendee_list(event)
     attendees.where(event_id: @event)
  end

end

app/controllers/admins/attendees_controller.rb
class Admins::AttendeesController < AdminsController
  before_action :check_if_admin

  def create
    @attendee = Attendee.new(attendee_params)
    #new_attendee = Attendee.new(user_id: @user.id, event_id: @event.id, user_role: 'user')

    if @attendee.save
      redirect_to '/admin/attendees'
    else
      render :new
    end
  end

  def new
    @attendee = Attendee.new
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.users
  end

  def destroy
    # would have perhaps been better to use nested resources, but not enough time.
    @attendence = Attendee.find_by(:event_id => params[:event_id], :user_id => params[:id])
    @attendence.destroy

    redirect_to "/admins/attendees/#{params[:event_id]}"  #todo may be a helper method for this?
    # redirect_to admins_attendee_path ??
  end

  private

  def attendee_params
    params.require(:attendee).permit(:title, :description, :date_time, :max_tix)   #JLW -don't seem to have to put event_id in here. Weird.
  end

end

app/controllers/attendee_controller.rb
class AttendeeController < ApplicationController
end

app/views/admins/attendees/_form.html.erb
<%= form_for [:admins, @attendee] do |f| %>  <!--need :admins since namespaced-->
	<div class="admin">
    <fieldset>
    	<legend>Add attendee</legend>

      <p><%= f.label "Person", :class =>'admin-field' %></p>
      <!-- <p><%#= f.collection_select(:id,@attendee,:id,:name) %></p> -->

      <p><%= f.submit :class =>'admin-btn' %></p>
    </fieldset>
	</div>
<% end %>

<!--http://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html-->

app/views/admins/attendees/index.html.erb
<div class="admin-pages">
    <h2>Choose an event to see the attendees</h2>

    <table class="admin" border="1">
      <tr><th>Title</th><th>Tickets Sold</th><th>Maximum Tickets</th></tr>
    <% @events.each do |event| %>
        <tr>
            <td class="admin-left"><%= link_to event.title, admins_attendee_path(event) %></td>
            <td><%= event.tickets_sold %></td>
            <td><%= event.max_tix %></td>
        </tr>
    <% end %>
    </table>

    <%= render :partial => 'admins/pages/admin' %>
</div>

app/views/admins/attendees/new.html.erb
<!-- <h2>new attendee</h2> -->

<%#= form_for [:admins, @attendee] do |f| %>

    <%= render 'form' %>

<%# end %>

<%= render :partial => 'admins/pages/admin' %>

app/views/admins/attendees/show.html.erb
<div class="admin-pages">
    <h1><%= @event.title %></h1>
    <h2>Attendees</h2>
    <table class="admin" border="1">
      <tr>
        <th>Name</th>
        <th><%= link_to 'Add attendee to event', new_admins_attendee_path(@event), method: :get %></th>
      </tr>
      <% @attendees.each do |attendee| %>
          <tr>
            <td><%= attendee.name %></td>
            <td><%= link_to 'Remove from event', admins_attendee_path(attendee, :event_id => @event.id), method: :delete %></td>
          </tr>
        <% end %>

    </table>
    <%= render :partial => 'admins/pages/admin' %>
</div>